# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_book_price_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price_book',
            field=models.IntegerField(default=36),
        ),
    ]
