# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20171223_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_fio', models.CharField(max_length=100)),
                ('writer_book', models.CharField(max_length=100)),
            ],
        ),
    ]
